### ISSUE TITLE
dont run docker as root

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/dockerfiler#11]
Be sure that created dockerfile dont run golem as root by default

> Migrated from https://github.com/ThinkR-open/golem/issues/115

**Comment by VincentGuyader** [comment]
We will do it in two steps. We will allow a user to choose the USER to use in dockerfiler::dock_from_renv. However, we will let golem decide who launches the app. This allows us to distinguish the user who installs the dependencies from the user who launches the application. Thus, there will be a user parameter in both dockerfiler::dock_from_renv and golem::add_dockerfile_with_renv_*.
