### ISSUE TITLE
Can't get my golem app running in the docker container locally. Please help. I have been stuck at this point from very long time and couldn't progress my work.

### ISSUE THREAD

**Issue by bindu07** [ThinkR-open/dockerfiler#33]
I can't get my app running on the docker container. I have been building and running the images using the following commads.

-> For building a docker image -> docker build -t test .

-> To spin the image in the container -> docker run --rm -p 3838:3838 test

I have tried changing commands in dockerfiles , but it takes a while to built it. 

It just says that it couldn't find the package name and the image doesn't run at all. I will provide more details if you guys need anything else. 

 options('shiny.port'=3838,shiny.host='0.0.0.0');Obigolem::run_app()
Error in loadNamespace(name) : there is no package called ‘Obigolem’
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

I am attaching my dockerfile below if it's helpful for someone to see.  What did I miss??? 

![ObiDockerError](https://user-images.githubusercontent.com/17426318/173734678-59eb27c0-3844-46a2-9538-917f721e9e55.png)

![OBI_DOCKERT2png](https://user-images.githubusercontent.com/17426318/173734954-e372ca98-8bb6-4a9f-8d60-e61d5f60265d.png)

**Comment by bindu07** [comment]
@ColinFay - Please help with this issue :)

**Comment by ColinFay** [comment]
Generally this happens when the golem app doesn't build,  i.e. the shiny application containing the app fails to install, but the docker image still build. 

Can you retry building the docker image while keeping an eye on what the docker compiler logs? And see if the application installation step works correctly ?

**Comment by bindu07** [comment]
worked when libfontconfig1-dev  is added to the app-get list in the dockerfile. still the docker build fails sometimes. not sure why!!
