### ISSUE TITLE
Turn Dockerfile to `{dockerfiler}` object

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/dockerfiler#5]
It would ne nice to be able to read a Dockerfile and manipulate it

**Comment by JosiahParry** [comment]
Giving this a +1 would like this functionality

**Comment by michkam89** [comment]
giving +1 to this as well :)

**Comment by ColinFay** [comment]
Note to self: i think this can be pretty straightforward to implement as long as we don't check for the validity of the Dockerfile and assume the user inputs a valid one

**Comment by JosiahParry** [comment]
Any progress on this here fella?

**Comment by VincentGuyader** [comment]
done
