### ISSUE TITLE
[BUG] `golem::add_dockerfile_shinyproxy` adds `"` around `NA`

### ISSUE THREAD

**Issue by danielquintao** [ThinkR-open/dockerfiler#61]
**Description**
It seems that the Dockerfile generated by the function `golem::add_dockerfile_shinyproxy` inserts quotes around `NA` in lines `RUN Rscript -e 'remotes::install_version(..., version="NA")'`. Replacing `"NA"` by `NA` seems to fix the Dockerfile and allow for proper building.

**To Reproduce**
1. Installed version of golem: 0.4.1
2. Clone or download [ColinFay's tidytuesday201942 example](https://github.com/ColinFay/tidytuesday201942)
3. Use `golem::add_dockerfile_shinyproxy(from="rocker/shiny-verse:4.3.1")` 
4. Try `docker built -t tidytuesday .` and see error `ERROR [12/26] RUN Rscript -e 'remotes::install_version("pkgload",upgrade="never", version = "NA")'`
5. replace all thge `"NA"` in the Dockerfile by `NA`  and save the file
6. `docker build -t tidytuesday .` again; it should work now

**Expected behavior**
Building the Docker image should have worked without modifying the Dockerfile (although this is a quite simple change, it would be nice to  have things as automatic as possible).

**Additional context**
* Also tested with [golemR6 example](https://github.com/ColinFay/golemexamples/tree/master/golemR6) and got the same behaviour.

**Comment by VincentGuyader** [comment]
```
  if (length(packages_on_cran > 0)) {
    ping <- mapply(function(dock, ver, nm) {
      res <- dock$RUN(sprintf("Rscript -e 'remotes::install_version(\"%s\",upgrade=\"never\", version = \"%s\")'", 
        nm, ver))
    }, ver = packages_on_cran, nm = names(packages_on_cran), 
      MoreArgs = list(dock = dock))
  }
```

if nm is a `NA` it's create `"NA"`

**Comment by VincentGuyader** [comment]
you can try with the new version on `remotes::install_github("ThinkR-open/dockerfiler")` ?

Regards

**Comment by danielquintao** [comment]
> you can try with the new version on `remotes::install_github("ThinkR-open/dockerfiler")` ?
> 
> Regards

It worked fine! Thank you very much

Regards
