### ISSUE TITLE
fix: tests that rely on renv shouldn't be performed on CRAN [urgent]

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/dockerfiler#64]
Feedbacks after issues with revdeps for `{knitr}` & `{withr}` on CRAN : 

When performing the revdep checks on CRAN for `{dockerfiler}`, the tests call `{renv}` which requires all packages used in deps to be available. By definition, they are not : for example, if the `{withr}` maintainers submit a new version of the package, `{withr}` is not available on CRAN at that exact moment, and the revdevp checks fail.

Fix : all tests that call `{renv}` should be `skip_on_cran()`

**Comment by VincentGuyader** [comment]
I think that as long as the version currently in master doesn't depend on renv, then it's ok...

**Comment by VincentGuyader** [comment]
0.2.2 is "on his way on cran"
