### ISSUE TITLE
[BUG] Dockerfile_base fails to execute when generated with `add_dockerfile_with_renv_shinyproxy()`

### ISSUE THREAD

**Issue by campbead** [ThinkR-open/dockerfiler#66]
`add_dockerfile_with_renv_shinyproxy()` generates files normally as expected.  However the current version of `renv`seems to be causing difficulty with deploying.  

Here is the `Dockerfile_base` produced by `add_dockerfile_with_renv_shinyproxy()` for my project:

```
FROM rocker/verse:4.2.2
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages(c("renv","remotes"))'
COPY renv.lock renv.lock
RUN R -e 'renv::restore()'
```

However when this files is used to created a docker container using this command `docker build -f Dockerfile_base --progress=plain -t golem.test.project_base .`

I get the following error:

<img width="691" alt="Screenshot 2023-10-26 at 7 52 53 PM" src="https://github.com/ThinkR-open/golem/assets/2994053/e91d6bc8-d5e0-403f-b634-39e212c01812">

I have attempted fix by changing `Dockerfile_base` to force an install of an older version of `renv` to:

```
FROM rocker/verse:4.2.2
RUN mkdir -p /usr/local/lib/R/etc/ /usr/lib/R/etc/
RUN echo "options(renv.config.pak.enabled = TRUE, repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl', Ncpus = 4)" | tee /usr/local/lib/R/etc/Rprofile.site | tee /usr/lib/R/etc/Rprofile.site
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_version("renv", version = "0.17.3")'
COPY renv.lock renv.lock
RUN R -e 'renv::restore()'
```

which results in a successful build when using the `docker build` command.

This seems to be a problem with `renv` but am asking for help here for two reasons.

1. I am not sure exactly how to document this issue for a bug report to `renv` and any help with that would be awesome
2. The current way `Dockerfile_base` files are created using `add_dockerfile_with_renv_shinyproxy()` is using the most current version of `renv` and not the version of `renv` used in the lockfile.  It would be nice to at least have this option with this package prevent this particular bug.

Thank you for your help.

**To Reproduce**
1. create new golem project with some minimal amount of content
3. run `renv::init()`to create a lockfile
4. run `add_dockerfile_with_renv_shinyproxy(lockfile = "renv.lock")`
5. run the first `docker build` command in the generated `README` file

**session info**

─ Session info ────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       macOS Ventura 13.3.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Pacific/Auckland
 date     2023-10-26
 rstudio  2023.09.1+494 Desert Sunflower (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────────────────────────────────────
 ! package     * version date (UTC) lib source
 P attempt       0.3.1   2020-05-03 [?] CRAN (R 4.2.0)
 P cachem        1.0.6   2021-08-19 [?] CRAN (R 4.2.0)
 P callr         3.7.3   2022-11-02 [?] CRAN (R 4.2.0)
 P cli           3.5.0   2022-12-20 [?] CRAN (R 4.2.0)
 P config        0.3.1   2020-12-17 [?] CRAN (R 4.2.0)
 P crayon        1.5.2   2022-09-29 [?] CRAN (R 4.2.0)
 P desc          1.4.2   2022-09-08 [?] CRAN (R 4.2.0)
 P devtools      2.4.5   2022-10-11 [?] CRAN (R 4.2.0)
 P digest        0.6.31  2022-12-11 [?] CRAN (R 4.2.0)
 P dockerfiler   0.2.1   2023-01-18 [?] CRAN (R 4.2.0)
 P ellipsis      0.3.2   2021-04-29 [?] CRAN (R 4.2.0)
 P fastmap       1.1.0   2021-01-25 [?] CRAN (R 4.2.0)
 P fs            1.5.2   2021-12-08 [?] CRAN (R 4.2.0)
 P glue          1.6.2   2022-02-24 [?] CRAN (R 4.2.0)
 P golem         0.4.1   2023-06-05 [?] CRAN (R 4.2.0)
 P htmltools     0.5.4   2022-12-07 [?] CRAN (R 4.2.0)
 P htmlwidgets   1.6.0   2022-12-15 [?] CRAN (R 4.2.0)
 P httpuv        1.6.7   2022-12-14 [?] CRAN (R 4.2.0)
 P jsonlite      1.8.4   2022-12-06 [?] CRAN (R 4.2.0)
 P later         1.3.0   2021-08-18 [?] CRAN (R 4.2.0)
 P lifecycle     1.0.3   2022-10-07 [?] CRAN (R 4.2.0)
 P magrittr      2.0.3   2022-03-30 [?] CRAN (R 4.2.0)
 P memoise       2.0.1   2021-11-26 [?] CRAN (R 4.2.0)
 P mime          0.12    2021-09-28 [?] CRAN (R 4.2.0)
 P miniUI        0.1.1.1 2018-05-18 [?] CRAN (R 4.2.0)
 P pak           0.6.0   2023-08-29 [?] RSPM (R 4.2.0)
 P pkgbuild      1.4.0   2022-11-27 [?] CRAN (R 4.2.0)
 P pkgload       1.3.2   2022-11-16 [?] CRAN (R 4.2.0)
 P prettyunits   1.1.1   2020-01-24 [?] CRAN (R 4.2.0)
 P processx      3.8.0   2022-10-26 [?] CRAN (R 4.2.0)
 P profvis       0.3.7   2020-11-02 [?] CRAN (R 4.2.0)
 P promises      1.2.0.1 2021-02-11 [?] CRAN (R 4.2.0)
 P ps            1.7.2   2022-10-26 [?] CRAN (R 4.2.0)
 P purrr         1.0.0   2022-12-20 [?] CRAN (R 4.2.0)
 P R6            2.5.1   2021-08-19 [?] CRAN (R 4.2.0)
 P Rcpp          1.0.9   2022-07-08 [?] CRAN (R 4.2.0)
 P remotes       2.4.2   2021-11-30 [?] CRAN (R 4.2.0)
 P renv          1.0.3   2023-09-19 [?] RSPM (R 4.2.0)
 P rlang         1.0.6   2022-09-24 [?] CRAN (R 4.2.0)
 P rprojroot     2.0.3   2022-04-02 [?] CRAN (R 4.2.0)
 P rstudioapi    0.14    2022-08-22 [?] CRAN (R 4.2.0)
 P sessioninfo   1.2.2   2021-12-06 [?] CRAN (R 4.2.0)
 P shiny         1.7.4   2022-12-15 [?] CRAN (R 4.2.0)
 P stringi       1.7.8   2022-07-11 [?] CRAN (R 4.2.0)
 P stringr       1.5.0   2022-12-02 [?] CRAN (R 4.2.0)
 P urlchecker    1.0.1   2021-11-30 [?] CRAN (R 4.2.0)
 P usethis       2.1.6   2022-05-25 [?] CRAN (R 4.2.0)
 P vctrs         0.5.1   2022-11-16 [?] CRAN (R 4.2.0)
 P withr         2.5.0   2022-03-03 [?] CRAN (R 4.2.0)
 P xtable        1.8-4   2019-04-21 [?] CRAN (R 4.2.0)
 P yaml          2.3.6   2022-10-18 [?] CRAN (R 4.2.0)

 [1] /Users/adamc/Library/Caches/org.R-project.R/R/renv/library/golem.test.actions-7c1a2f83/R-4.2/aarch64-apple-darwin20
 [2] /Users/adamc/Library/Caches/org.R-project.R/R/renv/sandbox/R-4.2/aarch64-apple-darwin20/fd29d0b8

 P ── Loaded and on-disk path mismatch.

**Comment by VincentGuyader** [comment]
👍  no issue with  : 
+ golem from CRAN
+ no pre-created renv.lock file

golem::add_dockerfile_with_renv_shinyproxy(output_dir = "deploy")

![image](https://github.com/ThinkR-open/dockerfiler/assets/10470699/8989f245-811d-4e95-a028-ef629506cb74)

👎 issue with  :
+ golem from CRAN
+ pre-created renv.lock file with renv::init()

golem::add_dockerfile_with_renv_shinyproxy(lockfile = "renv.lock",output_dir = "deploy")

![image](https://github.com/ThinkR-open/dockerfiler/assets/10470699/f61b93b4-a6ba-4d43-b3d6-0c17ba74a397)

👍  no issue with  : 
+ golem from CRAN
+ pre-created renv.lock file with attachment::create_renv_for_prod()

attachment::create_renv_for_prod()
golem::add_dockerfile_with_renv_shinyproxy(output_dir = "deploy",lockfile = "renv.lock.prod" )


👎 issue with  : 
+ golem from CRAN
+ pre-created renv.lock file with attachment::create_renv_for_dev()
+ dockerfiler from github

attachment::create_renv_for_dev(output = "renv.lock.dev")
golem::add_dockerfile_with_renv_shinyproxy(output_dir = "deploy",lockfile = "renv.lock.dev" )

but not the same issue : 

![image](https://github.com/ThinkR-open/dockerfiler/assets/10470699/7bba3c6e-6eaf-466b-81a1-52b79702e38d)


👎 issue with  : 
+ golem from CRAN
+ pre-created renv.lock file with attachment::create_renv_for_dev()
+ dockerfiler from CRAN


![image](https://github.com/ThinkR-open/dockerfiler/assets/10470699/79d5c2bc-cec3-44aa-aade-1878a40ff2fb)

**Comment by VincentGuyader** [comment]
each time setting `renv.config.pak.enabled = FALSE` correct the issue...

**Comment by VincentGuyader** [comment]
I will set FALSE by default... the issue seems more an issue with pak than renv or dockerfiler

**Comment by campbead** [comment]
Perhaps this bugfix can be its own release version?  I would definitely help my deployment pipeline if it were available off CRAN.

**Comment by VincentGuyader** [comment]
Can you please confirm me that the branch https://github.com/ThinkR-open/dockerfiler/tree/rc_2.2 correct this issue ?

Regards

**Comment by campbead** [comment]
Yes I can confirm that using rc_2.2 allowed a succesful `golem::add_dockerfile_with_renv_shinyproxy(lockfile = "renv.lock",output_dir = "deploy")` execution.

Thank you.

**Comment by VincentGuyader** [comment]
0.2.2 is "on his way on cran"
