### ISSUE TITLE
Native pipe operator breaks usage with R < 4.1.0

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [ThinkR-open/dockerfiler#76]
The native pipe operator is only available starting with R >= 4.1.0

https://github.com/ThinkR-open/dockerfiler/blob/5ef486d101246a3b788c3b3e41af40b6cb2dfd04/R/dock_from_renv.R#L150-L151

https://github.com/ThinkR-open/dockerfiler/blob/5ef486d101246a3b788c3b3e41af40b6cb2dfd04/dev/flat_dock_from_renv.Rmd#L189-L190

## Options

- Replace native pipe
- Bump minimum R version in DESCRIPTION to 4.1.0 (👉 #77)

**Comment by VincentGuyader** [comment]
oops, I hadn't thought of that. 
I suggest removing the pipes from the code, so that older versions of R are still usable.
